(() => {
  const root = (window.Shooter = window.Shooter || {});
  const { WEAPONS } = root.constants;

  Object.assign(WEAPONS, {
    pistol: {
      key: "pistol",
      name: "手枪",
      damage: 18,
      fireInterval: 0.24,
      magSize: 12,
      reloadTime: 1.05,
      spreadDeg: 2.2,
      bulletsPerShot: 1,
      bulletSpeed: 980,
      kick: 2.2,
    },
    rifle: {
      key: "rifle",
      name: "步枪",
      damage: 12,
      fireInterval: 0.095,
      magSize: 30,
      reloadTime: 1.35,
      spreadDeg: 3.2,
      bulletsPerShot: 1,
      bulletSpeed: 1080,
      kick: 2.6,
    },
    shotgun: {
      key: "shotgun",
      name: "霰弹枪",
      damage: 7,
      fireInterval: 0.78,
      magSize: 6,
      reloadTime: 1.55,
      spreadDeg: 14,
      bulletsPerShot: 7,
      bulletSpeed: 900,
      kick: 5.2,
    },
    smg: {
      key: "smg",
      name: "冲锋枪",
      damage: 8,
      fireInterval: 0.065,
      magSize: 42,
      reloadTime: 1.45,
      spreadDeg: 6.5,
      bulletsPerShot: 1,
      bulletSpeed: 980,
      kick: 2.4,
    },
    dmr: {
      key: "dmr",
      name: "连发步枪",
      damage: 24,
      fireInterval: 0.26,
      magSize: 14,
      reloadTime: 1.35,
      spreadDeg: 1.4,
      bulletsPerShot: 1,
      bulletSpeed: 1200,
      kick: 3.2,
    },
    sniper: {
      key: "sniper",
      name: "狙击枪",
      damage: 60,
      fireInterval: 0.95,
      magSize: 5,
      reloadTime: 1.8,
      spreadDeg: 0.6,
      bulletsPerShot: 1,
      bulletSpeed: 1550,
      kick: 6.2,
    },
    hmg: {
      key: "hmg",
      name: "重型机枪",
      damage: 14,
      fireInterval: 0.045,
      magSize: 120,
      reloadTime: 2.2,
      spreadDeg: 7.5,
      bulletsPerShot: 1,
      bulletSpeed: 1100,
      kick: 3.6,
      bulletR: 3.2,
      bulletColor: "#ffd36f",
    },
    epic_smg: {
      key: "epic_smg",
      name: "史诗·冲锋枪",
      damage: 11,
      fireInterval: 0.052,
      magSize: 58,
      reloadTime: 1.05,
      spreadDeg: 5.2,
      bulletsPerShot: 1,
      bulletSpeed: 1120,
      kick: 2.7,
      bulletR: 3.2,
      bulletColor: "#ff6fb0",
    },
    epic_dmr: {
      key: "epic_dmr",
      name: "史诗·连发步枪",
      damage: 30,
      fireInterval: 0.22,
      magSize: 18,
      reloadTime: 1.15,
      spreadDeg: 1.0,
      bulletsPerShot: 1,
      bulletSpeed: 1350,
      kick: 3.6,
      bulletR: 3.2,
      bulletColor: "#ff6fb0",
    },
    epic_sniper: {
      key: "epic_sniper",
      name: "史诗·狙击枪",
      damage: 90,
      fireInterval: 0.82,
      magSize: 7,
      reloadTime: 1.55,
      spreadDeg: 0.35,
      bulletsPerShot: 1,
      bulletSpeed: 1850,
      kick: 6.8,
      bulletR: 3.6,
      bulletColor: "#ff6fb0",
    },
    epic_hmg: {
      key: "epic_hmg",
      name: "史诗·重型机枪",
      damage: 18,
      fireInterval: 0.038,
      magSize: 160,
      reloadTime: 1.9,
      spreadDeg: 6.2,
      bulletsPerShot: 1,
      bulletSpeed: 1250,
      kick: 4.0,
      bulletR: 3.6,
      bulletColor: "#ff6fb0",
    },
    rocket_launcher: {
      key: "rocket_launcher",
      name: "火箭筒 (RPG-7)",
      damage: 150,
      fireInterval: 1.2,
      magSize: 1,
      reloadTime: 0.8,
      spreadDeg: 1.0,
      bulletsPerShot: 1,
      bulletSpeed: 600, // scaled for game
      kick: 10,
      isRocket: true,
      explosionRadius: 30
    },
    grenade: {
      key: "grenade",
      name: "手雷",
      damage: 75,
      fireInterval: 1.0,
      magSize: 1,
      reloadTime: 0.5,
      spreadDeg: 0,
      bulletsPerShot: 1,
      bulletSpeed: 520,
      kick: 2,
      isGrenade: true,
    },
    thunder_gun: {
      key: "thunder_gun",
      name: "雷暴枪",
      damage: 40,
      fireInterval: 1.6,
      magSize: 1,
      reloadTime: 0.5,
      spreadDeg: 0,
      bulletsPerShot: 1,
      bulletSpeed: 0,
      kick: 4,
      isThunder: true,
    },
  });

  root.weapons = {
    list() {
      return Object.values(WEAPONS);
    },
    get(key) {
      return WEAPONS[key] || null;
    },
  };
})();
